name = "shorter"
main = "index.js"

compatibility_date = "2024-03-26"
compatibility_flags = [ "nodejs_compat" ]

[site]
bucket = "./src"

[[kv_namespaces]]
id = "34d831990f2a4a9ea880e04eb9c27d70"
binding = "SHORTER_URLS"
