name = "shorter"
main = "index.js"
compatibility_date = "2023-11-17"

[placement]
mode = "smart"

[site]
bucket = "./assets"

[[kv_namespaces]]
id = "34d831990f2a4a9ea880e04eb9c27d70"
preview_id = "34d831990f2a4a9ea880e04eb9c27d70"
binding = "SHORTER_URLS"
