name: Deploy API documentation
permissions:
  contents: read

on:
  push:

jobs:
  deploy-doc:
    name: Deploy API documentation on Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Output debug info
        run: echo "BUMP_SH_DOCID=$BUMP_SH_DOCID"
      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          token: ${{ secrets.BUMP_SH_TOKEN }}
          file: api-docs.json
