name: Diff API documentation
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:

jobs:
  api-diff:
    name: Check API diff on Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Comment pull request with API diff
        uses: bump-sh/github-action@ce67b2e1690da8cb4b5c1333dec4b5acdbfd99cc
        with:
          doc: 41ac0bef-ea5a-44a1-a763-eb10d17d4b71
          token: ${{ secrets.BUMP_SH_TOKEN }}
          file: api-docs.json
          command: diff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
