name: ESLint

on:
  push:

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v4

      - name: "🔧 setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: "🛸 install eslint html plugins"
        run: npm i --omit=optional --include=dev --no-fund --progress=false

      - name: "🔍 lint code"
        run: npm run lint
